[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test'
solc = '0.8.26'
fs_permissions = [{ access = 'read', path = './' }, { access = 'read-write', path = './deploy-out' }]
evm_version = 'cancun'

remappings = [
    '@layerzerolabs/onft-evm/=lib/devtools/packages/onft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
